task_4/Bascket_test_project/Test_prj/Test_prj/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='products'))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_4/Bascket_test_project/Test_prj/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('index/', mainapp.main, name='index'),
    path('form/', mainapp.add_product, name='form'),
]

task_4/Bascket_test_project/Test_prj/mainapp/models.py
# В каталоге приложения создать модель, которая должна хранить информацию о поступивших товарах: название,
# дату поступления, цену, единицу измерения, имя поставщика. Выполнить миграции.

from django.db import models


class GoodsItem(models.Model):
    title = models.CharField(max_length=32, unique=True)
    date_of_receipt = models.DateTimeField(auto_now_add=True)
    price = models.FloatField()
    unit = models.CharField(max_length=16)
    supplier_name = models.CharField(max_length=32)
    quantity = models.PositiveIntegerField()

task_4/Bascket_test_project/Test_prj/mainapp/forms.py
from django.forms import ModelForm
from mainapp.models import GoodsItem


class GoodsAddForm(ModelForm):
    class Meta:
        model = GoodsItem
        fields = ['title', 'price', 'unit', 'supplier_name', 'quantity']

    def __init__(self, *args, **kwargs):
        super(GoodsAddForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = 'Введите название товара'
        self.fields['price'].widget.attrs['placeholder'] = 'Введите цену за еденицу товара'
        self.fields['unit'].widget.attrs['placeholder'] = 'Введите еденицу измерения товара'
        self.fields['supplier_name'].widget.attrs['placeholder'] = 'Введите поставщика товара'
        self.fields['quantity'].widget.attrs['placeholder'] = 'Введите количество товара'

task_4/Bascket_test_project/Test_prj/mainapp/views.py
# Функции-контроллеры должны отвечать за загрузку списка товаров на главной странице и добавление товара на второй
# странице. ## 8. В файле views.py каталога проекта реализовать два контроллера в формате функций. Первый должен
# извлекать все записи из модели с каталогом товаром и передавать переменную со списком товаров в контекст шаблона
# (html-страница со списком товаров). Во втором контроллере должен создаваться объект формы для ввода данных о товаре
# и выполняться рендеринг шаблона страницы добавления товара. В контекст шаблона необходимо передавать объект формы.


from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from mainapp.models import GoodsItem
from mainapp.forms import GoodsAddForm
from django.shortcuts import render, HttpResponseRedirect


def main(request):
    context = {
        'title': 'GeekShop',
        'products': GoodsItem.objects.all(),
    }
    return render(request, 'mainapp/index.html', context)


def add_product(request):
    if request.method == 'POST':
        form = GoodsAddForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно добавили товар!')
            return HttpResponseRedirect(reverse('products:form'))
    else:
        form = GoodsAddForm()
    context = {'form': form}
    return render(request, 'mainapp/form.html', context)

task_4/Bascket_test_project/Test_prj/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}{% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'products:index' %}">Products list</a>
        <a class="navbar-brand" href="{% url 'products:form' %}">Form</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
            </ul>
        </div>
    </div>
</nav>

<!-- Content -->
{% block content %}{% endblock %}

<!-- Footer -->


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>
</html>

task_4/Bascket_test_project/Test_prj/mainapp/templates/mainapp/form.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-lg-7">
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать товар</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'products:form' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.title.id_for_label }}">Название товара</label>
                                {{ form.title }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена товара</label>
                                {{ form.price }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.unit.id_for_label }}">Еденица измерения</label>
                            {{ form.unit }}
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.supplier_name.id_for_label }}">Поставщик товара
                                </label>
                            {{ form.supplier_name }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                                {{ form.quantity }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-4 mb-0">
                        <input class="btn btn-primary btn-block" type="submit" value="Создать товар">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'products:index' %}">Вернуться к списку</a></div>
            </div>
        </div>
    </div>
{% endblock %}

task_4/Bascket_test_project/Test_prj/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <h4>{{ product.title }}</h4>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.supplier_name }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}